services:
  - type: web
    name: n8n
    env: node
    plan: standard
    buildCommand: pnpm install --frozen-lockfile && pnpm run build
    startCommand: pnpm start
    healthCheckPath: /
    envVars:
      - key: NODE_OPTIONS
        value: "--max-old-space-size=4096"
      - key: NODE_ENV
        value: production
    buildFilter:
      paths:
        - packages/**/*
        - package.json
        - pnpm-lock.yaml
        - render.yaml 